ing_aeronautico_morse={
        "A":{"Alfa/Alpha","● ▬"},
        "B":{"Bravo","▬ ● ● ●"},
        "C":{"Charlie","▬ ● ▬ ●"},
        "D":{"Delta","▬ ● ●",},
        "E":{"Echo","●"},
        "F":{"Foxtrot","● ● ▬ ●"},
        "G":{"Golf","▬ ▬ ●"},
        "H":{"Hotel","● ● ● ●"},
        "I":{"India","● ●"},
        "J":{"Juliett","● ▬ ▬ ▬"},
        "K":{"Kilo","▬ ● ▬"},
        "L":{"Lima","● ▬ ● ●"},
        "M":{"Mike","▬ ▬"},
        "N":{"November","▬ ●"},
        "O":{"Oscar","▬ ▬ ▬"},
        "P":{"Papa","● ▬ ▬ ●"},
        "Q":{"Quebec","▬ ▬ ● ▬" },
        "R":{"Romeo","● ▬ ●"},
        "S":{"Sierra","● ● ●"},
        "T":{"Tango","▬"},
        "U":{"Uniform","● ● ▬"},
        "V":{"Victor","● ● ● ▬"},
        "W":{"Whiskey","● ▬ ▬"},
        "X":{"X-ray","▬ ● ● ▬"},
        "Y":{"Yankee","▬ ▬ ● ●"},
        "Z":{"Zulu","▬ ▬ ▬ ▬ ▬"},
        " ":{"Space"," "},
        ".":{"Dot","▬ ● ▬ ● ▬"},
        ",":{"Comma","▬ ▬ ● ● ▬ ▬"},
        "?":{"Question","● ● ▬ ▬ ● ●"},
        "'":{"Quotes","● ▬ ● ● ▬ ●"},
        "/":{"Slash","▬ ● ● ▬ ●"},
        "0":{"Zero","▬ ▬ ▬ ▬ ▬"},
        "1":{"One","● ▬ ▬ ▬ ▬"},
        "2":{"Two","● ● ▬ ▬ ▬"},
        "3":{"Three","● ● ● ▬ ▬"},
        "4":{"Four","● ● ● ● ▬"},
        "5":{"Five","● ● ● ● ●"},
        "6":{"Six","▬ ● ● ● ●"},
        "7":{"Seven","▬ ▬ ● ● ●"},
        "8":{"Eight","▬ ▬ ▬ ● ●"},
        "9":{"Nine","▬ ▬ ▬ ▬ ●"}
        }



matriz=[
        ["A","Alfa","● ▬","AL FAH"],
        ["B","Bravo","▬ ● ● ●","BRAH VOH"],
        ["C","Charlie","▬ ● ▬ ●","CHAR LEE"],
        ["D","Delta","▬ ● ●","DELL TAH"],
        ["E","Echo","●","ECK OH"],
        ["F","Foxtrot","● ● ▬ ●","FOKS TROT"],
        ["G","Golf","▬ ▬ ●","GOLF"],
        ["H","Hotel","● ● ● ●","HOH TELL"],
        ["I","India","● ●","IN DEE AH"],
        ["J","Juliett","● ▬ ▬ ▬","JEW LEE ETT"],
        ["K","Kilo","▬ ● ▬","KEY LOH"],
        ["L","Lima","● ▬ ● ●","LEE MAH"],
        ["M","Mike","▬ ▬","MIKE"],
        ["N","November","▬ ●","NO VEMBER"],
        ["O","Oscar","▬ ▬ ▬","OSS CAH"],
        ["P","Papa","● ▬ ▬ ●","PAH PAH"],
        ["Q","Quebec","▬ ▬ ● ▬","KEH BECK"],
        ["R","Romeo","● ▬ ●","ROW ME OH"],
        ["S","Sierra","● ● ●","SEE AIRRAH"],
        ["T","Tango","▬","TANG OH"],
        ["U","Uniform","● ● ▬","YOU NEE FORM"],
        ["V","Victor","● ● ● ▬","VIK TAH"],
        ["W","Whiskey","● ▬ ▬","WISS KEY"],
        ["X","X-ray","▬ ● ● ▬","ECKS RAY"],
        ["Y","Yankee","▬ ▬ ● ●","YANG KEY"],
        ["Z","Zulu","▬ ▬ ▬ ▬ ▬","ZOO LOO"],
        [" ","Space"," "," "],
        [".","Dot","▬ ● ▬ ● ▬",""],
        [",","Comma","▬ ▬ ● ● ▬ ▬",""],
        ["?","Question","● ● ▬ ▬ ● ●",""],
        ["'","Quotes","● ▬ ● ● ▬ ●",""],
        ["/","Slash","▬ ● ● ▬ ●",""],
        ["0","Zero","▬ ▬ ▬ ▬ ▬",""],
        ["1","One","● ▬ ▬ ▬ ▬",""],
        ["2","Two","● ● ▬ ▬ ▬",""],
        ["3","Three","● ● ● ▬ ▬",""],
        ["4","Four","● ● ● ● ▬",""],
        ["5","Five","● ● ● ● ●",""],
        ["6","Six","▬ ● ● ● ●",""],
        ["7","Seven","▬ ▬ ● ● ●",""],
        ["8","Eight","▬ ▬ ▬ ● ●",""],
        ["9","Nine","▬ ▬ ▬ ▬ ●",""]]
